### PR TITLE
Monitoring of different shells

### PR DESCRIPTION
**Pull request by sanderu**
Monitoring config and execution of different shells

### CODE REVIEW

**Comment by kovacs-andras** [comment]
I'm pretty sure these shell watchers  will make an unbearably huge amount of noise.
Maybe it's a good idea to watch for the "exotics" but watching the  execution of dash on debian/ubuntu etc. or bash, or busybox on other systems will most of the time trace the operating system itself.

But watching the system-wide rc and profile files are not a bad idea, I usually do the same. 👍

**Comment by sanderu** [comment]
I totally agree that these will be noisy if all of them are enabled by default.

You're totally correct about dash/bash on Debian/Ubuntu would be less than ideal.
However, it should be easy to enable/disable monitoring for the shells if need be.

I have no problem in having them disabled by default and then users can enable if they have the need for it.

**Comment by Neo23x0** [comment]
I'd like to add only rules that can be used "as they are". 
Therefore I'd like to deactivate all rules that cover default shells on any well-known distribution. 

I think that we can leave the second block active but I'd comment out the first one. 
Is "fish" or "dash" a default shell somewhere?

**Comment by sanderu** [comment]
dash is the Debian OS default for system shell and bash is also installed and used for users.

I haven't come across any OS that uses fish as default.

**Comment by kovacs-andras** [comment]
GhostBSD use fish as a default shell afaik.

**Comment by Neo23x0** [comment]
I cannot edit the pull request. Please make the changes. Otherwise I cannot pull it to the `master` branch.

**Comment by sanderu** [comment]
Fixed - you should be able to do the edits now.

**Review by its0x08 — APPROVED** [review]

**Pull request merged**
