### PR TITLE
cleanup

### PR DESCRIPTION
**Pull request by kovacs-andras**
Hi!
I removed a few rules which seemed unnecessary but I see even more.
Please check and consider.

### CODE REVIEW

**Comment by kovacs-andras** [comment]
@Pierre-Gronau-ndaal please correct me if I'm wrong. Thanks!

**Comment by Pierre-Gronau-ndaal** [comment]
del duplicates:
https://unix.stackexchange.com/questions/375433/etc-sudoers-vs-etc-sudoers-d-file-for-enabling-sudo-for-a-user#375435

**Comment by Pierre-Gronau-ndaal** [comment]
VMware Tools:

according to

https://docs.vmware.com/en/VMware-Tools/12.2.0/com.vmware.vsphere.vmwaretools.doc/GUID-08BB9465-D40A-4E16-9E15-8C016CC8166F.html

Open VMware Tools replaced VMware Tools

but we will find both so we have to cover maybe both situations

example for 32 bit Linux:

- https://docs.vmware.com/en/VMware-Tools/10.3/rn/VMware-Tools-10325-Release-Notes.html

reference
=======

- https://docs.vmware.com/en/VMware-Tools/12.2.0/com.vmware.vsphere.vmwaretools.doc/GUID-C48E1F14-240D-4DD1-8D4C-25B6EBE4BB0F.html
- https://github.com/vmware/open-vm-tools
- https://kb.vmware.com/s/article/1014294
- https://kb.vmware.com/s/article/2073803
- https://www.vmware.com/pdf/vmware-tools-101-standalone-user-guide.pdf

`RHEL 8.8
rpm -ql open-vm-tools
/etc/pam.d/vmtoolsd
/etc/vmware-tools
/etc/vmware-tools/poweroff-vm-default
/etc/vmware-tools/poweron-vm-default
/etc/vmware-tools/resume-vm-default
/etc/vmware-tools/scripts
/etc/vmware-tools/scripts/vmware
/etc/vmware-tools/scripts/vmware/network
/etc/vmware-tools/statechange.subr
/etc/vmware-tools/suspend-vm-default
/etc/vmware-tools/tools.conf.example
/etc/vmware-tools/vgauth
/etc/vmware-tools/vgauth.conf
/etc/vmware-tools/vgauth/schemas
/etc/vmware-tools/vgauth/schemas/XMLSchema-hasFacetAndProperty.xsd
/etc/vmware-tools/vgauth/schemas/XMLSchema-instance.xsd
/etc/vmware-tools/vgauth/schemas/XMLSchema.dtd
/etc/vmware-tools/vgauth/schemas/XMLSchema.xsd
/etc/vmware-tools/vgauth/schemas/catalog.xml
/etc/vmware-tools/vgauth/schemas/datatypes.dtd
/etc/vmware-tools/vgauth/schemas/saml-schema-assertion-2.0.xsd
/etc/vmware-tools/vgauth/schemas/xenc-schema.xsd
/etc/vmware-tools/vgauth/schemas/xml.xsd
/etc/vmware-tools/vgauth/schemas/xmldsig-core-schema.xsd
/usr/bin/VGAuthService
/usr/bin/vm-support
/usr/bin/vmhgfs-fuse
/usr/bin/vmtoolsd
/usr/bin/vmware-alias-import
/usr/bin/vmware-checkvm
/usr/bin/vmware-hgfsclient
/usr/bin/vmware-namespace-cmd
/usr/bin/vmware-rpctool
/usr/bin/vmware-toolbox-cmd
/usr/bin/vmware-vgauth-cmd
/usr/bin/vmware-xferlogs
/usr/lib/.build-id
/usr/lib/.build-id/04
/usr/lib/.build-id/04/ac414a36fe4aed21e80ced2339b7820e58b017
/usr/lib/.build-id/0f
/usr/lib/.build-id/0f/0f6ed51b62676728d0e2746da5389103f6895b
/usr/lib/.build-id/1d
/usr/lib/.build-id/1d/429f5b6d2a252fea89b070f7d044a125c6b979
/usr/lib/.build-id/26
/usr/lib/.build-id/26/d0b52eb409384347ae754d50dac8e36b657aaa
/usr/lib/.build-id/2e
/usr/lib/.build-id/2e/b3b45d938eb4f0c89220754172ea6a059ce19c
/usr/lib/.build-id/30
/usr/lib/.build-id/30/fe5064b2f10765fd97553a209aee09a2be1d61
/usr/lib/.build-id/32
/usr/lib/.build-id/32/086114679be1e524f0823631a816f2c9e764fd
/usr/lib/.build-id/3e
/usr/lib/.build-id/3e/c6ca5ba85769dadf5b301803dbefc5531b46ab
/usr/lib/.build-id/3e/f1ecd751f81e548d546d6891941e8380861d70
/usr/lib/.build-id/4d
/usr/lib/.build-id/4d/48fc6f5f65847b9fac724ca345472233e606b2
/usr/lib/.build-id/51
/usr/lib/.build-id/51/77f5260a460e77becc1a4d7ca8c272f1d6f45d
/usr/lib/.build-id/52
/usr/lib/.build-id/52/871c7de6903f89803105370f718fc559001989
/usr/lib/.build-id/54
/usr/lib/.build-id/54/2ec3f08c28ce32ad66bf6c1a5dc0d00e354af0
/usr/lib/.build-id/5b
/usr/lib/.build-id/5b/14ba626f3688e5e4ba00402092a6fa186d6b22
/usr/lib/.build-id/5c
/usr/lib/.build-id/5c/8252479d8bb33e6d6128ffab3ae517a1e4ddf6
/usr/lib/.build-id/61
/usr/lib/.build-id/61/8b588225adefbb90670cd531652ec91b30f560
/usr/lib/.build-id/73
/usr/lib/.build-id/73/a3655c88202d436298e0fd5a5789203c0b6909
/usr/lib/.build-id/75
/usr/lib/.build-id/75/c46a8d03d7be935ca78e7882d9dea83095d6ce
/usr/lib/.build-id/9f
/usr/lib/.build-id/9f/4c1d26febc8a797b012dee7cb54fbd5fa35a45
/usr/lib/.build-id/ad
/usr/lib/.build-id/ad/9fb65b97a4ab7dab02682ce5c3f36875d28c85
/usr/lib/.build-id/b5
/usr/lib/.build-id/b5/a1f2f06eaf97a700e0e085c97c3d648c89bcce
/usr/lib/.build-id/b8
/usr/lib/.build-id/b8/5bb978ed6f9469cccbe89a604183709b3236b3
/usr/lib/.build-id/c6
/usr/lib/.build-id/c6/4478bb0ca5c0aa0e6f7f10039b67f8b19ce8f1
/usr/lib/.build-id/d4
/usr/lib/.build-id/d4/ccf7de431de92f727f28ba3c1602e197c35a44
/usr/lib/.build-id/d4/de7b84bbf0eb6bdc57d98f02987c39f8eec5d1
/usr/lib/.build-id/e9
/usr/lib/.build-id/e9/22f26aa9ef5bd01b77becabaf81984e356ec11
/usr/lib/.build-id/ef
/usr/lib/.build-id/ef/5fbc69fe9def68a7413e2f608069898126f36b
/usr/lib/.build-id/f2
/usr/lib/.build-id/f2/658f1f5589e295bd623987e87783cccf7b1323
/usr/lib/.build-id/ff
/usr/lib/.build-id/ff/00c01852225a36eb9980fab66c5f34144d05f5
/usr/lib/modules-load.d/open-vm-tools.conf
/usr/lib/systemd/system/vgauthd.service
/usr/lib/systemd/system/vmtoolsd.service
/usr/lib/udev/rules.d/99-vmware-scsi-udev.rules
/usr/lib64/libDeployPkg.so.0
/usr/lib64/libDeployPkg.so.0.0.0
/usr/lib64/libguestStoreClient.so.0
/usr/lib64/libguestStoreClient.so.0.0.0
/usr/lib64/libguestlib.so.0
/usr/lib64/libguestlib.so.0.0.0
/usr/lib64/libhgfs.so.0
/usr/lib64/libhgfs.so.0.0.0
/usr/lib64/libvgauth.so.0
/usr/lib64/libvgauth.so.0.0.0
/usr/lib64/libvmtools.so.0
/usr/lib64/libvmtools.so.0.0.0
/usr/lib64/open-vm-tools
/usr/lib64/open-vm-tools/plugins
/usr/lib64/open-vm-tools/plugins/common
/usr/lib64/open-vm-tools/plugins/common/libhgfsServer.so
/usr/lib64/open-vm-tools/plugins/common/libvix.so
/usr/lib64/open-vm-tools/plugins/vmsvc
/usr/lib64/open-vm-tools/plugins/vmsvc/libappInfo.so
/usr/lib64/open-vm-tools/plugins/vmsvc/libcomponentMgr.so
/usr/lib64/open-vm-tools/plugins/vmsvc/libdeployPkgPlugin.so
/usr/lib64/open-vm-tools/plugins/vmsvc/libgdp.so
/usr/lib64/open-vm-tools/plugins/vmsvc/libguestInfo.so
/usr/lib64/open-vm-tools/plugins/vmsvc/libguestStore.so
/usr/lib64/open-vm-tools/plugins/vmsvc/libpowerOps.so
/usr/lib64/open-vm-tools/plugins/vmsvc/libresolutionKMS.so
/usr/lib64/open-vm-tools/plugins/vmsvc/libtimeSync.so
/usr/lib64/open-vm-tools/plugins/vmsvc/libvmbackup.so
/usr/share/doc/open-vm-tools
/usr/share/doc/open-vm-tools/AUTHORS
/usr/share/doc/open-vm-tools/ChangeLog
/usr/share/doc/open-vm-tools/NEWS
/usr/share/doc/open-vm-tools/README
/usr/share/licenses/open-vm-tools
/usr/share/licenses/open-vm-tools/COPYING
/usr/share/open-vm-tools
/usr/share/open-vm-tools/messages
/usr/share/open-vm-tools/messages/de
/usr/share/open-vm-tools/messages/de/VGAuthCli.vmsg
/usr/share/open-vm-tools/messages/de/VGAuthService.vmsg
/usr/share/open-vm-tools/messages/de/libvgauth.la.vmsg
/usr/share/open-vm-tools/messages/de/toolboxcmd.vmsg
/usr/share/open-vm-tools/messages/de/vmtoolsd.vmsg
/usr/share/open-vm-tools/messages/en
/usr/share/open-vm-tools/messages/en/VGAuthCli.vmsg
/usr/share/open-vm-tools/messages/en/VGAuthService.vmsg
/usr/share/open-vm-tools/messages/en/libvgauth.la.vmsg
/usr/share/open-vm-tools/messages/en/toolboxcmd.vmsg
/usr/share/open-vm-tools/messages/en/vmtoolsd.vmsg
/usr/share/open-vm-tools/messages/es
/usr/share/open-vm-tools/messages/es/VGAuthCli.vmsg
/usr/share/open-vm-tools/messages/es/VGAuthService.vmsg
/usr/share/open-vm-tools/messages/es/libvgauth.la.vmsg
/usr/share/open-vm-tools/messages/es/toolboxcmd.vmsg
/usr/share/open-vm-tools/messages/es/vmtoolsd.vmsg
/usr/share/open-vm-tools/messages/fr
/usr/share/open-vm-tools/messages/fr/VGAuthCli.vmsg
/usr/share/open-vm-tools/messages/fr/VGAuthService.vmsg
/usr/share/open-vm-tools/messages/fr/libvgauth.la.vmsg
/usr/share/open-vm-tools/messages/fr/toolboxcmd.vmsg
/usr/share/open-vm-tools/messages/fr/vmtoolsd.vmsg
/usr/share/open-vm-tools/messages/it
/usr/share/open-vm-tools/messages/it/VGAuthCli.vmsg
/usr/share/open-vm-tools/messages/it/VGAuthService.vmsg
/usr/share/open-vm-tools/messages/it/libvgauth.la.vmsg
/usr/share/open-vm-tools/messages/it/toolboxcmd.vmsg
/usr/share/open-vm-tools/messages/it/vmtoolsd.vmsg
/usr/share/open-vm-tools/messages/ja
/usr/share/open-vm-tools/messages/ja/VGAuthCli.vmsg
/usr/share/open-vm-tools/messages/ja/VGAuthService.vmsg
/usr/share/open-vm-tools/messages/ja/libvgauth.la.vmsg
/usr/share/open-vm-tools/messages/ja/toolboxcmd.vmsg
/usr/share/open-vm-tools/messages/ja/vmtoolsd.vmsg
/usr/share/open-vm-tools/messages/ko
/usr/share/open-vm-tools/messages/ko/VGAuthCli.vmsg
/usr/share/open-vm-tools/messages/ko/VGAuthService.vmsg
/usr/share/open-vm-tools/messages/ko/libvgauth.la.vmsg
/usr/share/open-vm-tools/messages/ko/toolboxcmd.vmsg
/usr/share/open-vm-tools/messages/ko/vmtoolsd.vmsg
/usr/share/open-vm-tools/messages/zh_CN
/usr/share/open-vm-tools/messages/zh_CN/VGAuthCli.vmsg
/usr/share/open-vm-tools/messages/zh_CN/VGAuthService.vmsg
/usr/share/open-vm-tools/messages/zh_CN/libvgauth.la.vmsg
/usr/share/open-vm-tools/messages/zh_CN/toolboxcmd.vmsg
/usr/share/open-vm-tools/messages/zh_CN/vmtoolsd.vmsg
/usr/share/open-vm-tools/messages/zh_TW
/usr/share/open-vm-tools/messages/zh_TW/VGAuthCli.vmsg
/usr/share/open-vm-tools/messages/zh_TW/VGAuthService.vmsg
/usr/share/open-vm-tools/messages/zh_TW/libvgauth.la.vmsg
/usr/share/open-vm-tools/messages/zh_TW/toolboxcmd.vmsg
/usr/share/open-vm-tools/messages/zh_TW/vmtoolsd.vmsg`

**Comment by kovacs-andras** [comment]
> del duplicates:
> 
> * https://unix.stackexchange.com/questions/375433/etc-sudoers-vs-etc-sudoers-d-file-for-enabling-sudo-for-a-user#375435
> * https://superuser.com/questions/869144/why-does-the-system-have-etc-sudoers-d-how-should-i-edit-it

There are 2 rules also for "Sudoers file changes"

**Comment by kovacs-andras** [comment]
@Pierre-Gronau-ndaal thank you for double-checking it!

Do you really use 32bit systems or applications these days? Apart from AV products like... mcafee? - which you should exclude anyways as they make a ton of noise. (tbh I haven't seen their agents for a few years) But in my opinion the last rule should be enough to detect all 32bit calls.

The release notes you sent says:
_"linux.iso supports Linux guest operating systems Red Hat Enterprise Linux (RHEL) 6, SUSE Linux Enterprise Server (SLES) 11 (see [Known Issues](https://docs.vmware.com/en/VMware-Tools/10.3/rn/VMware-Tools-10325-Release-Notes.html#knownissues)), and Ubuntu 12.04. linux.iso also supports other distributions with glibc versions 2.11 and later."_
All of these are EOL for a long time.

And the next sentence says to use open-vm-tools instead:
_For later versions of the above guest operating systems, Red Hat Enterprise Linux (RHEL) 7 and later, SUSE Linux Enterprise Server (SLES) 12 and later, Ubuntu 14.04 and later, it is recommended to install the OS vendor provided open-vm-tools_

The rule I removed with `path=/usr/lib/vmware-tools` is not part of the open-vm-tools package and neither in the rpm query you sent.

**Pull request merged**
